### ISSUE TITLE
Should you be forcing compiler to 4.9 on ubuntu 15.10 and 16.04?

### ISSUE THREAD

**Issue by hughperkins** [torch/distro#101]
Just a question.  Should you be forcing compiler to 4.9 on ubuntu 15.10/16.04?  I need to do something like as follows.  I think.  Not 100% sure :-P  https://github.com/hughperkins/distro/blob/7933a352af973f765e1e1b9bdf8ca763e03a0bbd/install.sh#L53-L57

```
# handle ubuntu 15.10, 16.04, which default to gcc 5
if [[ $(gcc -dumpversion | cut -d . -f 1) == 5 ]]; then {
  export CC=gcc-4.9
  export CXX=g++-4.9
} fi
```

**Comment by soumith** [comment]
i think instead of that, we really need to add the _FORCE_INLINES flag to our cmake and let distro compile on higher GCC versions.

**Comment by hughperkins** [comment]
Note that host_config.h will block build, on gcc > 4.9, unless you hack it, or unless a new version of cuda has/will be released.

**Comment by hughperkins** [comment]
(For that matter, if one was going to hack host_config.h, one could alternatively add the `_FORCE_INLINES` define inside the hack)

**Comment by hughperkins** [comment]
(and ... rather than hacking it... one could simply create a local file, with the same name, eg in `~/torch/install/include`, and simply ensure that directly is included prior to the cuda directory)
