### ISSUE TITLE
cannot open </torch/openface/models/openface/nn4.small2.v1.t7> in mode r  at torch/pkg/torch/lib/TH/THDiskFile.c

### ISSUE THREAD

**Issue by psakamoori** [torch/distro#108]
When trying to run openface - http://cmusatyalab.github.io/openface/demo-3-classifier/
I am seeing below issue.

psakhamo@ironmaiden:~/torch/openface$ ./batch-represent/main.lua -outDir data/mydataset/raw/feature -data data/mydataset/raw/align
/home/psakhamo/torch/install/bin/lua: .../psakhamo/torch/install/share/lua/5.1/trepl/init.lua:384: ...hamo/torch/install/share/lua/5.1/luarocks/loader.lua:154: Invalid data in manifest file for module torch (invalid data for torch scm-1)
stack traceback:
        [C]: in function 'error'
        .../psakhamo/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
        ./batch-represent/main.lua:3: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: ?

Any pointers on this

**Comment by psakamoori** [comment]
After re-installation...of torch...not seeing above issue.
But, stuck with below.


psakhamo@ironmaiden:~/torch/openface$ ./batch-represent/main.lua -outDir data/mydataset/raw/feature -data data/mydataset/raw/align
{
  batchSize : 50
  cuda : false
  outDir : "data/mydataset/raw/feature"
  cache : false
  imgDim : 96
  data : "data/mydataset/raw/align"
  model : "/home/psakhamo/torch/openface/models/openface/nn4.small2.v1.t7"
}
/home/psakhamo/torch/install/bin/lua: cannot open </home/psakhamo/torch/openface/models/openface/nn4.small2.v1.t7> in mode r  at /home/psakhamo/torch/pkg/torch/lib/TH/THDiskFile.c:649
stack traceback:
        [C]: ?
        [C]: in function 'DiskFile'
        .../psakhamo/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
        ./batch-represent/main.lua:33: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk

Any pointers on this, will be very helpful.

**Comment by psakamoori** [comment]
Solved this by

psakhamo@ironmaiden:~/torch/openface/models$ sh get-models.sh


====================================================
Downloading OpenFace models, which are copyright
Carnegie Mellon University and are licensed under
the Apache 2.0 License.

This will incur about 100MB of network traffic for the models.
====================================================

2016-05-03 15:14:09 URL:http://openface-models.storage.cmusatyalab.org/nn4.small2.v1.t7 [31510785/31510785] -> "openface/nn4.small2.v1.t7" [1]
2016-05-03 15:14:55 URL:http://openface-models.storage.cmusatyalab.org/celeb-classifier.nn4.small2.v1.pkl [4471339/4471339] -> "openface/celeb-class         ifier.nn4.small2.v1.pkl" [1]


====================================================
Verifying checksums.
====================================================

+ dlib/shape_predictor_68_face_landmarks.dat: successfully checked

+ openface/celeb-classifier.nn4.small2.v1.pkl: successfully checked

+ openface/nn4.small2.v1.t7: successfully checked

psakhamo@ironmaiden:~/torch/openface/models$ cd ..


Now facing below error

psakhamo@ironmaiden:~/torch/openface$ ./batch-represent/main.lua -outDir data/mydataset/raw/feature -data data/mydataset/raw/align
{
  batchSize : 50
  cuda : false
  outDir : "data/mydataset/raw/feature"
  cache : false
  imgDim : 96
  data : "data/mydataset/raw/align"
  model : "/home/psakhamo/torch/openface/models/openface/nn4.small2.v1.t7"
}
data/mydataset/raw/align
cache lotation:         /home/psakhamo/torch/openface/data/mydataset/raw/align/cache.t7
Creating metadata for cache.
{
  paths :
    {
      1 : "data/mydataset/raw/align"
    }
  split : 0
  verbose : true
  samplingMode : "balanced"
  sampleSize :
    {
      1 : 3
      2 : 96
      3 : 96
    }
  loadSize :
    {
      1 : 3
      2 : 96
      3 : 96
    }
}
/home/psakhamo/torch/install/bin/lua: .../psakhamo/torch/openface/batch-represent/dataset.lua:130: attempt to index global 'jit' (a nil value)
stack traceback:
        .../psakhamo/torch/openface/batch-represent/dataset.lua:130: in function '__init'
        .../psakhamo/torch/install/share/lua/5.1/torch/init.lua:91: in function <.../psakhamo/torch/install/share/lua/5.1/torch/init.lua:87>
        [C]: in function 'dataLoader'
        ...o/torch/openface/batch-represent/batch-represent.lua:19: in function 'batchRepresent'
        ./batch-represent/main.lua:42: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk

**Comment by psakamoori** [comment]
commenting this section (as I am running openface on Ubuntu)
As per this link "Luajit" is properly installed on my machine http://www.gammon.com.au/scripts/doc.php?lua=string.dump
Still seen this issue.
Finally. in ./batch-represent/dataset.lua @ line 130
Comment this section, solved the issue
   --if jit.os == 'OSX' then
     -- wc = 'gwc'
      --cut = 'gcut'
     -- find = 'gfind'
   --end

**Comment by AndrijKolomiets** [comment]
replace jit.os with ffi.os  also works

> 
--if jit.os == 'OSX' then
-- wc = 'gwc'
--cut = 'gcut'
-- find = 'gfind'
--end

**Comment by zwayn** [comment]
`/Users/julienzouein/torch/install/bin/luajit: cannot open </Users/julienzouein/Desktop/blade/Shadrone/Panda/OpenFace/openface/models/openface/nn4.v1.t7> in mode r  at /Users/julienzouein/torch/pkg/torch/lib/TH/THDiskFile.c:673
stack traceback:
	[C]: at 0x08536c60
	[C]: in function 'DiskFile'
	.../julienzouein/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	main.lua:33: in main chunk
	[C]: in function 'dofile'
	...uein/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x0108434cc0
`
got this issue and tried all the solutions given, none is actually working
I'm on a MacBook Pro- Retina 2012
