### ISSUE TITLE
install-deps fails on clean Mac OSX

### ISSUE THREAD

**Issue by edvenson** [torch/distro#109]
"bash install-deps" was failing on my OSX system with this error: "Error: No such keg: /usr/local/Cellar/gnuplot"

It looks like the culprit is this line in the script, which aborts the whole thing in the "set -e" context: https://github.com/torch/distro/blob/master/install-deps#L80

Running "brew install gnuplot" and then re-running "bash install-deps" led to success.

If someone can confirm that this is a bug I'm happy to submit a PR that'll deal with brew not having a pre-existing gnuplot. Just want to make sure I'm not doing something wrong.

**Comment by Atcold** [comment]
There was no `set -e` when I added that instruction.
Sorry for the crashing installation.
