### ISSUE TITLE
Is Lua installable on a pcc64le-based machine?

### ISSUE THREAD

**Issue by kuo000** [torch/distro#112]
Hi everyone,

I'm trying to install Torch on a pcc64le-based server. I was able to install CUDA and other dependencies. Afterwards, I simply ran the scripts **install-deps** and **install.sh**. The installation script **install.sh** failed with the message: 

>Installing Lua version: LUAJIT21
>CMake Error at exe/luajit-rocks/luajit-2.1/CMakeLists.txt:214 (MESSAGE):
>  architecture not supported.

I looked into the content of **CMakeLists.txt**, and it seems the supported architectures don't include pcc64le. I was just wondering whether Lua can be installed on a pcc64le-based machine at all?

Thanks.

**Comment by soumith** [comment]
try this:

TORCH_LUA_VERSION=LUA52 ./install.sh

on the other hand, i've never tested torch on PPC64ie

**Comment by kuo000** [comment]
Hi @soumith ,

Thanks for the suggestion. I'll give it a shot and (probably) come back to report my result.

Additionally, I looked at some performance benchmarks found online. It seems like LuaJIT can be much faster than Lua. Is this the case when using torch to train neural network models?

**Comment by soumith** [comment]
No, that's not the case when using torch because all of Torch's heavy lifting is done in C

**Comment by kuo000** [comment]
Thanks, @soumith . I gave it a try and got the following error:

> Prefix set to /home/test/torch/install
> Installing Lua version: LUA52
> Installing common Lua packages
> gcc -O2 -fPIC -I/home/test/torch/install/include -c src/lfs.c -o src/lfs.o
> gcc -shared -o lfs.so -L/home/test/torch/install/lib src/lfs.o
> Updating manifest for /home/test/torch/install/lib/luarocks/rocks
> No existing manifest. Attempting to rebuild...
> luafilesystem 1.6.3-1 is now built and installed in /home/test/torch/install/ (license: MIT/X11)
> 
> Updating manifest for /home/test/torch/install/lib/luarocks/rocks
> penlight scm-1 is now built and installed in /home/test/torch/install/ (license: MIT/X11)
> 
> gcc -O2 -fPIC -I/home/test/torch/install/include -c lua_cjson.c -o lua_cjson.o
> gcc -O2 -fPIC -I/home/test/torch/install/include -c strbuf.c -o strbuf.o
> gcc -O2 -fPIC -I/home/test/torch/install/include -c fpconv.c -o fpconv.o
> gcc -shared -o cjson.so -L/home/test/torch/install/lib lua_cjson.o strbuf.o fpconv.o
> Updating manifest for /home/test/torch/install/lib/luarocks/rocks
> lua-cjson 2.1devel-1 is now built and installed in /home/test/torch/install/ (license: MIT)
> 
> Installing core Torch packages
> gcc -O2 -fPIC -I/home/test/torch/install/include -c call.c -o call.o -Idynasm
> In file included from call.c:9:0:
> ffi.h:137:3: error: #error 
>  # error
>    ^
> 
> Error: Build error: Failed compiling object call.o

I have no idea what this is... I'll Google around a bit.

**Comment by soumith** [comment]
it stems from non-compatiblity with our package: https://github.com/facebook/luaffifb
We have not worked on a PPC64ie port of this package, but if you want to use the torch ecosystem, either porting this package to your architecture, or getting LuaJIT to work on PPC64ie is essential. It gives the ffi interface that some of the packages depend upon (such as cudnn.torch)

**Comment by kuo000** [comment]
Thanks @soumith for answering.

I'll consider my options and see if I want to try to get LuaJIT to work on ppc64le-based machines.

Closing the issue.

**Comment by kuo000** [comment]
Hi @soumith,

I'm thinking about trying to port **luaffifb** to ppc64le, yet I'm not sure how hard this will be. Will this require a lot of work, or some minor tweaking might achieve this?

Thanks.

**Comment by soumith** [comment]
Hi kuo000, if you work for ibm, @tomsercu said they have an internal fork of torch running on ppc64Ie

**Comment by tomsercu** [comment]
Hi @kuo000, check out https://github.com/PPC64
The repositories you find here (incl luajit and torch-distro) are modified to compile on power.
This is part of the OpenPower effort and maintained by folks at IBM.
Tom

**Comment by kuo000** [comment]
Hi @soumith, I don't work for IBM, but I actually found the ppc64 repositories pointed out by @tomsercu. I was able to compile torch and get it running on my ppc64le-based machine, simply by following the instructions: https://github.com/PPC64/torch-distro.

Thanks for helping along, @soumith  and @tomsercu .
