### ISSUE TITLE
Error installing Torch on Ubuntu 16.04

### ISSUE THREAD

**Issue by vatsal12117** [torch/distro#118]
followed the instructions on the page and getting the following errors -

vatsal@vatsal-Inspiron-7559:~/torch$ ./install.sh
Prefix set to /home/vatsal/torch/install
Installing Lua version: LUAJIT21
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to tputs' /home/vatsal/anaconda2/lib/libreadline.so: undefined reference totgoto'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to tgetflag' /home/vatsal/anaconda2/lib/libreadline.so: undefined reference toUP'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to tgetent' /home/vatsal/anaconda2/lib/libreadline.so: undefined reference totgetnum'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to PC' /home/vatsal/anaconda2/lib/libreadline.so: undefined reference totgetstr'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to `BC'
collect2: error: ld returned 1 exit status
make[2]: *** [exe/luajit-rocks/luajit-2.1/luajit] Error 1
make[1]: *** [exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/all] Error 2
make: *** [all] Error 2
./install.sh: line 82: /home/vatsal/torch/install/bin/luarocks: No such file or directory
Installing common Lua packages
./install.sh: line 86: /home/vatsal/torch/install/bin/luarocks: No such file or directory

I am running Ubuntu 16.04 with anaconda2. Please help!

**Comment by eneskemalergin** [comment]
I have exactly the same issue, with same specs...

**Comment by soumith** [comment]
I'd suggest changing this line: https://github.com/torch/distro/blob/master/install.sh#L35 from anaconda to anaconda2

**Comment by eneskemalergin** [comment]
I think that is not the problem because the error is not changed, @soumith

**Comment by anuragranj** [comment]
It seems like a problem with gcc-5.x. A possible hack is to add this into your CMakeLists.txt.
     
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")
Taken from: https://groups.google.com/d/msg/torch7/aj6cIPABUOA/QW0aSr2YAwAJ

**Comment by soumith** [comment]
no, the problem in this case is that they have anaconda2's readline that is conflicting with torch.
To fix this, remove anaconda from $PATH and $LD_LIBRARY_PATH, install torch, then add it back.

**Comment by alokranjan1234** [comment]
I am facing a similar issue,tried changing anaconda to anaconda3 in install.sh and also tried by removing anaconda from $PATH and $LD_LIBRARY_PATH .nothing seems to work ,still getting the same error ,after googling for some time i found it can be fixed by linking readline.so to libncurses or libterinfo but i have no idea how to do it in this case.

**Comment by alokranjan1234** [comment]
though it works with sudo but here "http://torch.ch/docs/getting-started.html" its mentioned not to use sudo . luarocks does not work after installing with sudo

**Comment by jkerfs** [comment]
I was able to resolve this issue my temporarily removing libreadline.so.  Try this:

```
mv ~/anaconda2/lib/libreadline.so ~/libreadline.so
make clean
./clean.sh
./install.sh
mv ~/libreadline.so ~/anaconda2/lib/libreadline.so
```

Cleaning the build directory is the important part.  I believe if you modify the install.sh to replace anaconda with anaconda2 that will work too if you clean the build directory before attempting to install again.

**Comment by vatsal12117** [comment]
Changing anaconda to anaconda2 in install.sh and cleaning the build directory did work. But now the installation gets stuck after the line  - MAGMA not found. Compiling without MAGMA support

Found Torch7 in /home/vatsal/torch/install
Looking for pthread.h
Looking for pthread.h - found
Looking for pthread_create
Looking for pthread_create - not found
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - found
Found Threads: TRUE
Found CUDA: /usr/local/cuda (found suitable version "7.5", minimum required is "6.5")
Found gcc >=5 and CUDA <=7.5, adding workaround C++ flags
MAGMA not found. Compiling without MAGMA support
*hangs*

**Comment by fivejjs** [comment]
Any updates?

**Comment by soumith** [comment]
this is now fixed via commit https://github.com/torch/distro/commit/c0e51b98acbb54e6655343a57152b6e711ffdc2b

**Comment by ChongqiuMao** [comment]
I amend this error with removing conda from $PATH and move the conda libreadline.so
