### ISSUE TITLE
Error installing cuda packages on ArchLinux

### ISSUE THREAD

**Issue by smiet** [torch/distro#119]
Installation fails on compilation of the cuda packages on an up-to-date system where everything is otherwise working perfectly. 
#### 

Found CUDA on your machine. Installing CUDA packages
-- Found Torch7 in /home/smiet/builds/torch/install
-- MAGMA not found. Compiling without MAGMA support
-- Automatic GPU detection failed. Building for all known architectures.
-- Compiling for CUDA architecture: 2.0 2.1(2.0) 3.0 3.5 5.0 5.2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/smiet/builds/torch/extra/cutorch/build
[  2%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
[  5%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
[  7%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
[ 10%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
[ 12%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
[ 15%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
[ 20%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
lib/THC/CMakeFiles/THC.dir/build.make:362: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o' failed
lib/THC/CMakeFiles/THC.dir/build.make:1356: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o' failed
lib/THC/CMakeFiles/THC.dir/build.make:220: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o' failed
lib/THC/CMakeFiles/THC.dir/build.make:1519: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o' failed
lib/THC/CMakeFiles/THC.dir/build.make:1691: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o' failed
lib/THC/CMakeFiles/THC.dir/build.make:2925: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o' failed
lib/THC/CMakeFiles/THC.dir/build.make:1970: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o' failed
lib/THC/CMakeFiles/THC.dir/build.make:1200: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o' failed
CMakeFiles/Makefile2:172: recipe for target 'lib/THC/CMakeFiles/THC.dir/all' failed
Makefile:127: recipe for target 'all' failed
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/smiet/builds/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/smiet/builds/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install
#### 

The compilation fails because the error limit is reached: 
#### 

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00005980_00000000-19_THCStorage.compute_52.cpp1.ii".
Compilation terminated.
CMake Error at THC_generated_THCStorage.cu.o.cmake:266 (message):
  Error generating file
  /home/smiet/builds/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o
#### 

and the error output is a whole lot of errors of this type: 
#### 

/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include/stddef.h(436): error: identifier "nullptr" is undefined

/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include/stddef.h(436): error: expected a ";"

/usr/include/c++/6.1.1/x86_64-pc-linux-gnu/bits/c++config.h(202): error: expected a ";"

/usr/include/c++/6.1.1/exception(63): error: expected a ";"

/usr/include/c++/6.1.1/exception(69): error: expected a ";"

/usr/include/c++/6.1.1/exception(77): error: expected a ";"

/usr/include/c++/6.1.1/exception(85): error: expected a ";"

/usr/include/c++/6.1.1/exception(95): error: expected a "{"

/usr/include/c++/6.1.1/bits/exception_ptr.h(64): error: function "std::current_exception" returns incomplete type "std::__exception_ptr::exception_ptr"

/usr/include/c++/6.1.1/bits/exception_ptr.h(64): error: expected a "{"
####

**Comment by npanpaliya** [comment]
See this issue https://github.com/torch/cutorch/issues/413
