### ISSUE TITLE
Install on Mac OS X 10.11.5 fails

### ISSUE THREAD

**Issue by fakufaku** [torch/distro#127]
Hi I tried to install following the [getting started](http://torch.ch/docs/getting-started.html) instructions on Mac OS X 10.11.5.

The installation fails with the following message

    -- Found Torch7 in /Users/scheibler/torch/install
    -- Autodetected CUDA architecture(s): 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /Users/scheibler/torch/extra/cunn/build
    [  5%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_RReLU.cu.o
    [  5%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_Sigmoid.cu.o
    [  5%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_PReLU.cu.o
    [ 11%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_LookupTable.cu.o
    [ 11%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SoftMarginCriterion.cu.o
    [ 11%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SmoothL1Criterion.cu.o
    [ 15%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SoftMax.cu.o
    [ 15%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SoftPlus.cu.o
    /Users/scheibler/torch/extra/cunn/lib/THCUNN/LookupTable.cu(333): error: more than one instance of overloaded function "std::pow" matches the argument list:
                function "pow(double, double)"
                function "std::pow(float, float)"
                function "std::pow(float, int)"
                argument types are: (float, double)

    1 error detected in the compilation of "/var/folders/jg/dwzzdbk97txcldqz4141dwdm0000gp/T//tmpxft_00014629_00000000-6_LookupTable.cpp1.ii".
    CMake Error at THCUNN_generated_LookupTable.cu.o.cmake:267 (message):
      Error generating file
      /Users/scheibler/torch/extra/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_LookupTable.cu.o

    make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_LookupTable.cu.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Error 2
    make: *** [all] Error 2

    Error: Build error: Failed building.
    
Any idea what could cause this ? I'd be grateful for any help!

**Comment by soumith** [comment]
hey there. while that's a valid error, it's the first i've seen it pop up, as most compilers have a relaxed constraint on it. 

I've fixed it just now via commits: https://github.com/torch/cunn/pull/303 and https://github.com/torch/distro/commit/f95379d8512ab96939b0d797c489bbaedf7fa313

Just running this command in a terminal: luarocks install cunn
should fix it for you.

**Comment by fakufaku** [comment]
Hi @soumith, thanks for your time! In fact I updated CUDA from 6.5 to 7.5, ran `clean.sh` and started over in a new terminal window, and the install went smooth this time...
