### ISSUE TITLE
Why not gcc 5?

### ISSUE THREAD

**Issue by fansgit** [torch/distro#132]
It seems that ubuntu 16.04 is supported from [install-deps@423cfba](https://github.com/torch/distro/commit/423cfba478928785ad7f81fbf5b87527697cdb6c). Why does it resist `gcc 5` but downgrade to `gcc 4.9`?

**Comment by soumith** [comment]
because of NVIDIA CUDA. CUDA 7.5 only supports (officially) upto gcc 4.9

**Comment by fansgit** [comment]
I think the common practice is allowing CPU-only mode for evaluation, then `gcc 5` on default becomes non-issue If it's supported.
