### ISSUE TITLE
Installing on macOS Sierra: problem with qt

### ISSUE THREAD

**Issue by erickrf** [torch/distro#156]
Apparently, qt is not yet installable in macOS Sierra via brew. I got the following error when running `install-deps`:

```
qt: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

Is there some workaround for it?

**Comment by soumith** [comment]
I've now made qt optional for OSX in the instal-deps script. The optional packages qtlua and qttorch will not install during the install process, but that's fine.
https://github.com/torch/distro/commit/d10e1f05d3d07356586c0d843c426f89aa986ae0
