### ISSUE TITLE
authentication problem when git clone cuda-convnet2.torch from .gitmodules

### ISSUE THREAD

**Issue by BTNC** [torch/distro#158]
Hi,

I faced authentication problem when "git clone git@github.com:soumith/cuda-convnet2.torch.git" in .gitmodules on windows. After I switch to "git clone https://github.com/soumith/cuda-convnet2.torch.git", it can clone the repository. I think that line in .gitmodules could be updated.

Thanks,

**Comment by soumith** [comment]
this is now removed in master
