### ISSUE TITLE
Installation error on CentOS 6.4

### ISSUE THREAD

**Issue by abria** [torch/distro#16]
Hi,

I am trying to install Torch on a workstation running CentOS 6.4. However, when I run the script

curl -sk https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash

I get the following error: ==> Only Ubuntu and Fedora distributions are supported.

In your self-contained Torch installation page (https://github.com/torch/distro) I read "Tested on Ubuntu 14.04, CentOS/RHEL 6.3 and OSX".

Is there something I am missing or CenOS is not really supported? If not, is there any workaround?

Thank you for in advance for your support.

Alessandro

**Comment by alexbw** [comment]
Hello,
The core of what install-deps does for CentOS would be

```
            sudo yum install -y cmake curl readline-devel ncurses-devel \
                                gcc-c++ gcc-gfortran git gnuplot unzip \
                                nodejs npm libjpeg-turbo-devel libpng-devel \
                                ImageMagick GraphicsMagick-devel fftw-devel \
                                sox-devel sox SDL2-devel zeromq3-devel \
                                qt-devel qtwebkit-devel sox-plugins-freeworld
            install_openblas
```

Can you let me know if that works? If so, then I'll remove the checks that require Fedora or Ubuntu to include CentOS. Is this an EC2 instance? If so, is it a public AMI?

Could you also run

```
grep -q "ID=fedora" /etc/os-release
```

That might fail, but Fedora and CentOS are not too far apart...

**Comment by abria** [comment]
Thank you very much for the prompt response.

It seems not all the packages could be installed:
```
Package cmake-2.8.12.2-4.el6.x86_64 already installed and latest version
Package curl-7.19.7-40.el6_6.4.x86_64 already installed and latest version
Package readline-devel-6.0-4.el6.x86_64 already installed and latest version
Package ncurses-devel-5.7-3.20090208.el6.x86_64 already installed and latest version
Package gcc-c++-4.4.7-11.el6.x86_64 already installed and latest version
Package gcc-gfortran-4.4.7-11.el6.x86_64 already installed and latest version
Package git-1.7.1-3.el6_4.1.x86_64 already installed and latest version
Package gnuplot-4.2.6-2.el6.x86_64 already installed and latest version
Package unzip-6.0-1.el6.x86_64 already installed and latest version
No package nodejs available.
No package npm available.
Package libjpeg-turbo-devel-1.2.1-3.el6_5.x86_64 already installed and latest version
Package 2:libpng-devel-1.2.49-1.el6_2.x86_64 already installed and latest version
Package ImageMagick-6.5.4.7-7.el6_5.x86_64 already installed and latest version
No package GraphicsMagick-devel available.
Package fftw-devel-3.2.1-3.1.el6.x86_64 already installed and latest version
Package sox-devel-14.2.0-6.el6.x86_64 already installed and latest version
Package sox-14.2.0-6.el6.x86_64 already installed and latest version
No package SDL2-devel available.
No package zeromq3-devel available.
Package 1:qt-devel-4.6.2-28.el6_5.x86_64 already installed and latest version
No package qtwebkit-devel available.
No package sox-plugins-freeworld available.
```

I am going to search for alternative package names and let you know. BTW, my CentOS is not an Amazon EC2 instance. It runs on a powerful workstation (64 CPU cores, 256 GB of RAM) that we have in our lab.  We need a framework for deep learning and yours seems the best candidate :-).

As to your latest command, the CentOS equivalent is:

```
grep CentOS /etc/centos-release
```

which produces the output
```
CentOS release 6.4 (Final)
```

**Comment by abria** [comment]
Hi,
I finally installed all the required dependencies except `sox-plugins-freeworld`. I had to manually install (i.e. compile from src)  `nodejs`, `GraphicsMagick-devel`, and `SDL2-devel`.

However, when launching the installation script at

https://raw.githubusercontent.com/torch/ezinstall/master/install-luajit+torch

I get this error:

```
Scanning dependencies of target libqtcore
[100%] Building CXX object packages/qtcore/CMakeFiles/libqtcore.dir/qtcore.cpp.o
/tmp/luarocks_qtlua-scm-1-3609/qtlua/packages/qtcore/qtcore.cpp: In function ‘int qurl_tolocalfile(lua_State*)’:
/tmp/luarocks_qtlua-scm-1-3609/qtlua/packages/qtcore/qtcore.cpp:551:12: error: ‘class QUrl’ has no member named ‘isLocalFile’
   if (!url.isLocalFile())
            ^
make[2]: *** [packages/qtcore/CMakeFiles/libqtcore.dir/qtcore.cpp.o] Error 1
make[1]: *** [packages/qtcore/CMakeFiles/libqtcore.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
```

I am a developer of Qt applications, and this sounds to me like I don't meet the minimum Qt version requirement (4.8?). I have Qt 4.7.4. Is there a workaround instead of updating my Qt (that would break other projects I am working to)? Can I avoid to build this piece of software?

Thank you for your support.

Alessandro

**Comment by alexbw** [comment]
That script you just ran had been replaced by this distribution's
install.sh script. I don't believe you need to run it. But I do think qt
4.8 is required (unsure) for Qt Lua applications. But do try just running
install.sh first.

**Comment by soumith** [comment]
@abria you can ignore those errors and forget about using the Qt interface (or install Qt 4.8 if you want to use it). The Qt interface is optional, and is accessed by typing "qlua" instead of "th" in the command-line.

Also, as @alexbw said, follow the two commands here: http://torch.ch/docs/getting-started.html#installing-torch

**Comment by abria** [comment]
Using the latest `install.sh` I get the same error, but this time it completed the build process and I am able to run `th` :-). 

@soumith thanks for your comment, that was exactly what I was going to ask.

Thank you guys, your real-time support was very helpful!

**Comment by alexbw** [comment]
@abria, do you have a short script that automatically builds dependencies on CentOS? Would be cool to add that to the dependency building script.

**Comment by abria** [comment]
No, I wish I do. I am not good in writing complex bash scripts, unfortunately. To solve the dependencies, I had to struggle a little bit as these required solving other dependencies which needed to be compiled manually. Some of these also required a bit of interaction (like `pecl`), uninstalling conflicting libs and adding new repos. Not an easy process to embed into a script (at least for me).

I think your CMake build process is just fine, as it searches for dependencies and tells the user which pieces are missing. I would just suggest to write a list of dependencies that anyone could solve before launching the `install.sh`/CMake process. Of course one could look into the scripts, but a more readable list that also tells which libs are really needed (like qt for qlua, and sox as I compiled w/o it) would be very useful.

**Comment by zhangxiangxiao** [comment]
Using EPEL should bring all the packages to your repository

**Comment by abria** [comment]
@zhangxiangxiao Your suggestion is very useful, and it should be included in the online installation guide! However, even after adding the EPEL repos, there are still 2 packages missing: `SDL2-devel` and `sox-plugins-freeworld`. Anyway I solved by manually download/configure/make/make install. Thank you!

**Comment by alexbw** [comment]
Are those packages requires? I'd be interested if the install succeeds
without them.

**Comment by soumith** [comment]
only sdl2-devel is required. the other one sox-plugins-* is optional.
sdl2-devel is required for the threads package.

**Comment by russellfei** [comment]
Is `sdl2-devel` and`sox` relevant to music/sound processing?
My CentOS didn't have that installed and all works well just for image processing.
Why `sdl-devel` is necessary?

**Comment by soumith** [comment]
sdl2 is needed for the threads package, in case you use it.

**Comment by mcsaucy** [comment]
It looks like sdl2 is no longer required for the threads package (https://github.com/torch/threads/commit/9665a4b99eed85ccfad1e03a581ff14428d6dace). Would omitting sdl2 break anything else?

**Comment by soumith** [comment]
it wouldn't break anything else. it is indeed not required by default anymore, I was thinking it's time to remove it from the default install.

**Comment by soumith** [comment]
fixd via #61
