### ISSUE TITLE
can not updating submodules

### ISSUE THREAD

**Issue by pobingwanghai** [torch/distro#177]
+++++++ Creating torch-activate.cmd luajit.cmd luarocks.cmd cmake.cmd
+++++++ Setup succeed!
+++++++ Updating submodules
fatal: Not a git repository (or any of the parent directories): .git
+++++++ Installing common lua packages

Error: File not found: rockspecs\luafilesystem-1.6.3-1.rockspec
+++++++ Installation error!

**Comment by BTNC** [comment]
I think you downloaded the distro-master.zip? Please run install.bat in a git cloned distro repository.

**Comment by pobingwanghai** [comment]
@BTNC sorry ,i forget to close this issue. I have succeed to install torch in windows,thanks a lot ,
