### ISSUE TITLE
updating specific package (torch for example)

### ISSUE THREAD

**Issue by yossibiton** [torch/distro#19]
Hi,

i want to update torch package, and i can find the way to do it right.

1. At first i tried "luarocks install torch", and it did installed the new version.
    But,  when i call torch.svd i get the error "Lapack not found in compile time.", 
    although lapack is installed for sure.
2. i went back to the original installation (by running "install.sh"). now everything works well but the  
    torch version is not the newest (i assume it's because how git handle submodules. the torch    
    submodule point to specific revision of torch repository but not to the HEAD revision).

**Comment by soumith** [comment]
there is a script called update.sh which updates the submodules. try running that first, and then install.sh

**Comment by yossibiton** [comment]
solved, thanks
