### ISSUE TITLE
Installing HDF5 fails

### ISSUE THREAD

**Issue by JonasHerzog** [torch/distro#191]
My aim is to run neuraltalk2 on windows 7. For that reason I need to install HDF5.
I tried luarocks install hdf5, but the command fails:

> Installing https://raw.githubusercontent.com/torch/rocks/master/hdf5-20-0.rockspec
Cloning into 'torch-hdf5'...
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="D:/distro-win/./install
/bin/.." -DCMAKE_INSTALL_PREFIX="D:\distro-win\.\install\luarocks\systree/lib/luarocks/rocks/hdf5/20-0";
nmake
cd build && nmake install
The System coud not find the Path.
Error: Build error: Failed installing.  

Any help would be appriciated

**Comment by BTNC** [comment]
git clone git://github.com/deepmind/torch-hdf5.git
cd torch-hdf5
edit [build_command](https://github.com/deepmind/torch-hdf5/blob/master/hdf5-0-0.rockspec#L20) to one line like:
` cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$(LUA_BINDIR)/.." -DCMAKE_INSTALL_PREFIX="$(PREFIX)" && $(MAKE)`
luarocks make hdf5-0-0.rockspec

**Comment by JonasHerzog** [comment]
Thanks that worked
