### ISSUE TITLE
Required path to run torch via a cron bash script

### ISSUE THREAD

**Issue by anonymau5** [torch/distro#195]
Hello

I am using a bash script to launch a service that is run through torch.
I have the services and torch working via bash. 
However when I attempt to run the task via cron I get a command not found for th.
I need to set the path for these commands to run via cron and am not sure where this path needs to go.

Thanks.

**Comment by anonymau5** [comment]
Nevermind, figured a way around it.

**Comment by indranil180** [comment]
can you please share the workaround ?

**Comment by CharAznableLoNZ** [comment]
Include the path to torch in the environment path in the beginning of the bash file.
