### ISSUE TITLE
Installation script doesn't work on Yosemite 

### ISSUE THREAD

**Issue by ekobir** [torch/distro#2]
Workaround: MACOSX_DEPLOYMENT_TARGET=10.9 ./install.sh

Thanks for providing this script.

Error occurs on
 OS Yosemite : 10.10.1 (14B25)
 XCode Version : 6.1.1 (6A2008a)
 Command Line Version:   6.1.1 (6A2008a)

 Error: 
 cc-4.9: warning: couldn't understand kern.osversion '14.0.0
Linking C shared library libluajit.dylib
gcc-4.9: warning: couldn't understand kern.osversion '14.0.0
Undefined symbols for architecture x86_64:
  "__Unwind_DeleteException", referenced from:
      _lj_err_unwind_dwarf in ljamalg.c.o
  "__Unwind_GetCFA", referenced from:
      _lj_err_unwind_dwarf in ljamalg.c.o
  "__Unwind_RaiseException", referenced from:
      _lj_err_throw in ljamalg.c.o
  "__Unwind_SetGR", referenced from:
      _lj_err_unwind_dwarf in ljamalg.c.o
  "__Unwind_SetIP", referenced from:
      _lj_err_unwind_dwarf in ljamalg.c.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [exe/luajit-rocks/luajit-2.1/libluajit.dylib] Error 1
make[1]: *** [exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/all] Error 2

**Comment by soumith** [comment]
does the workaround fix the issue? I can add that to the script if it does...

**Comment by ekobir** [comment]
Yes - it solves the issue. Thanks

**Comment by soumith** [comment]
I believe this was fixed via @alexbw 's changes. let me know if it works. thanks.
