### ISSUE TITLE
th

### ISSUE THREAD

**Issue by alexbw** [torch/distro#20]
I'd like to clarify the construction of the `th` script (distinct from `trepl`'s `th` binary) bundled with this distro.
It's my understanding that the `th` that the user calls is distinct from the `th` binary included with `trepl. The callable `th is a small shell script that has the following functionality:

 - Calls the `th` binary included with `trepl` using the local `luajit` install
 - Tells luajit where to look for modules before executing the `th` binary.
 - Loads all dependencies of `trepl` before executing the `th` binary.

Is that what it's doing?

**Comment by alexbw** [comment]
Also, is the `luajit` install with this distro patched to automatically call th? Is that what the 2.1 alpha is all about, or is this a separate phenomena? Whenever I invoke `luajit` it always brings up the 

```
$ luajit
LuaJIT 2.1.0-alpha -- Copyright (C) 2005-2014 Mike Pall. http://luajit.org/

 _____              _
|_   _|            | |
  | | ___  _ __ ___| |__
  | |/ _ \| '__/ __| '_ \
  | | (_) | | | (__| | | |
  \_/\___/|_|  \___|_| |_|

JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
th>
```

command prompt.

**Comment by soumith** [comment]
th is nothing but a lua-script (https://github.com/torch/trepl/blob/master/th).
It just does some argument-checking, and if you pass in a file to run (non-interpreter mode), then it calls dofile on that file.

If you run it in interpreter mode, then it starts the interpreter. Equivalent command to just start the interpreter is: `luajit  -e "require('trepl')()"`

luajit installed with the distro IS patched with the torch logo and nothing more.

**Comment by soumith** [comment]
the shell script that is actually installed as torch/install/bin/th is some weird luarocks magic that is absolutely not needed. It is just trying to run the script with the correct luajit I believe.

**Comment by soumith** [comment]
it's just luarocks trying to be smart.

**Comment by alexbw** [comment]
I see. It looks like LuaJIT hardcodes the paths it looks for modules in (
https://github.com/luvit/luajit-2.0/blob/master/src/luaconf.h#L32-L63) so
I'm just trying to see how the luarocks/torch system solved the "where are
my modules" problem in anticipation of making conda packages of lua modules.

It looks like this script explicitly updates the path, and is something we
can configure to look on a relative path, something that I think LuaJIT
can't do by default.
