### ISSUE TITLE
luarocks install hanging up

### ISSUE THREAD

**Issue by kzachery** [torch/distro#21]
First, let me say I am fairly new to Torch, Lua, and Ubuntu 14.04. I installed torch7 using the instructions listed at https://github.com/torch/distro. When I try and install other modules/packages using luarocks install, the installation hangs up. The following is an example of the output:
kzachery@DELL:~$ luarocks install nnx
Installing https://raw.githubusercontent.com/torch/rocks/master/nnx-0.1-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/nnx-0.1-1.rockspec... switching to 'build' mode
Cloning into 'lua---nnx'...

The next thing that happens is the download times out. This has happened with all of the modules/packages I have tried to install using luarocks. Not sure why downloads keep timing out. My work around is to do a manual git clone, cd to cloned directory, and then luarocks make rocks. The module directory paths for the git clone (e.g., https://github.com/torch/module_name.git) are always different than the site listed above. The thing is, when I use luarocks install, the https://raw.githubusercontent.com/torch/rocks/master/ site is always listed. Is there something I forgot to set in a configure file? Any assistance in this matter would be greatly appreciated.

-knz
kzachery@teledyne.com

**Comment by szagoruyko** [comment]
you're probably behind a firewall. what we do is modify clone method from ssh to https, check here https://github.com/torch/luajit-rocks/compare/master...szagoruyko:master

**Comment by kzachery** [comment]
Many Thanks! I will take a look.

**Comment by mcsaucy** [comment]
Did switching to https from ssh resolve your issue, @kzachery?

**Comment by kzachery** [comment]
My apologies! I thought I had replied to your message letting you know it worked. Yes, it resolved the timed-out issues I was having, and I was finally able to install Torch packages.

Many Thanks,
knz

**Comment by CuriousCat-7** [comment]
Thanks!
