### ISSUE TITLE
Installation on Archlinux fails because of dependency "qt5-webkit-ng" does not exist

### ISSUE THREAD

**Issue by berserkingyadis** [torch/distro#231]
On 64bit Archlinux the script [install-deps tries](https://github.com/torch/distro/blob/master/install-deps#L288) to install the package "qt5-webkit-ng",[ which does not exist anymore](https://www.archlinux.org/packages/?sort=&q=qt5-webkit-ng&maintainer=&flagged=). 

According to the Archlinux website, it got replaced by [qt5-webkit](https://www.archlinux.org/packages/extra/x86_64/qt5-webkit/)

I tried changing the above linked line in install-deps to the new package and everything installed fine, but this should be tested by others I think.

**Comment by nickalaskreynolds** [comment]
I also ran into the same error, so I just changed the line in the install-deps too.

**Comment by freeboson** [comment]
Same here. I fixed this in #234.
