### ISSUE TITLE
CUDA runtime error when doing simple SpatialConvoltionMM

### ISSUE THREAD

**Issue by jakezhaojb** [torch/distro#3]
The script is:

    require 'cutorch'
    require 'cunn'
    m = nn.Sequential()
    x = torch.rand(3,8,8):cuda()
    m:add(nn.SpatialConvolutionMM(3,1,2,2))
    m:cuda()
    print(m:forward(x))

I got the exception:

    ...src/torch-distro/install/share/lua/5.1/nn/Sequential.lua:38: /home/jz1672/torch_src/torch-distro/extra/cutorch/lib/THC/THCTensor.cu(31) : cuda runtime error : invalid argument
    stack traceback:
	[C]: in function 'updateOutput'
	...src/torch-distro/install/share/lua/5.1/nn/Sequential.lua:38: in function 'forward'
	[string "n:forward(x)"]:1: in main chunk
	[C]: in function 'xpcall'
	...ch_src/torch-distro/install/share/lua/5.1/trepl/init.lua:587: in function 'repl'
	...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00405330

I've tested this using different GPU card, namely NVIDIA Tesla and NVIDIA Titan.CUDA version includes 6.0.1 and 6.5.12. Any help is appreciated in advance.

**Comment by soumith** [comment]
hey @jakezhaojb i am seeing no issues for the same example. tested on both Titan and Tesla K40 on Ubuntu and RHEL6

**Comment by jakezhaojb** [comment]
Oops.. Is this caused by some CUDA compatibility problem? Really confused...

**Comment by soumith** [comment]
@jakezhaojb i suspect that you have an old version of torch on your system that you are not aware of.
I suggest that you cleanup any installation of torch first, using this script:
https://github.com/torch/ezinstall/raw/master/clean-old.sh
