### ISSUE TITLE
Put all the environment variables in one script

### ISSUE THREAD

**Issue by Rufflewind** [torch/distro#30]
It would be useful to put all the variable exports in its own file, say, `~/torch/bin/activate`.  This way, one only needs to add a single line to the shell rc file, and the user can also manually initialize the Torch environment via:

```sh
. ~/torch/bin/activate
```

**Comment by soumith** [comment]
I think that's pretty reasonable.

**Comment by Manasip8** [comment]
Can anyone suggest me the steps for windows ?
