### ISSUE TITLE
Install.sh failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by cswhjiang** [torch/distro#34]
```
./install.sh
Prefix set to /home/jwh/torch/install
Installing Lua version: LUAJIT21
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_BC_POW':
buildvm_x86.dasc:(.text+0x84b): undefined reference to `lj_wrap_pow'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_log':
buildvm_x86.dasc:(.text+0x269c): undefined reference to `lj_wrap_log'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_log10':
buildvm_x86.dasc:(.text+0x26cb): undefined reference to `lj_wrap_log10'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_exp':
buildvm_x86.dasc:(.text+0x26fa): undefined reference to `lj_wrap_exp'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_sin':
buildvm_x86.dasc:(.text+0x2729): undefined reference to `lj_wrap_sin'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_cos':
buildvm_x86.dasc:(.text+0x2758): undefined reference to `lj_wrap_cos'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_tan':
buildvm_x86.dasc:(.text+0x2787): undefined reference to `lj_wrap_tan'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_asin':
buildvm_x86.dasc:(.text+0x27b6): undefined reference to `lj_wrap_asin'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_acos':
buildvm_x86.dasc:(.text+0x27e5): undefined reference to `lj_wrap_acos'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_atan':
buildvm_x86.dasc:(.text+0x2814): undefined reference to `lj_wrap_atan'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_sinh':
buildvm_x86.dasc:(.text+0x2843): undefined reference to `lj_wrap_sinh'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_cosh':
buildvm_x86.dasc:(.text+0x2872): undefined reference to `lj_wrap_cosh'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_tanh':
buildvm_x86.dasc:(.text+0x28a1): undefined reference to `lj_wrap_tanh'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_pow':
buildvm_x86.dasc:(.text+0x28e5): undefined reference to `lj_wrap_pow'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_atan2':
buildvm_x86.dasc:(.text+0x2929): undefined reference to `lj_wrap_atan2'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_fmod':
buildvm_x86.dasc:(.text+0x296d): undefined reference to `lj_wrap_fmod'
collect2: error: ld returned 1 exit status
make[2]: *** [exe/luajit-rocks/luajit-2.1/luajit] Error 1
make[1]: *** [exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/all] Error 2
make: *** [all] Error 2
./install.sh: line 67: /home/jwh/torch/install/bin/luarocks: No such file or directory
Installing common Lua packages
./install.sh: line 71: /home/jwh/torch/install/bin/luarocks: No such file or directory
./install.sh: line 72: /home/jwh/torch/install/bin/luarocks: No such file or directory
./install.sh: line 73: /home/jwh/torch/install/bin/luarocks: No such file or directory
Installing core Torch packages
./install.sh: line 76: /home/jwh/torch/install/bin/luarocks: No such file or directory
```

Any suggestions? Thanks.

**Comment by soumith** [comment]
it is possible you are running torch in a VM.

Try the command: 

TORCH_LUA_VERSION=LUAJIT20 ./install.sh

**Comment by cswhjiang** [comment]
Thanks. It works.

**Comment by lanseyege** [comment]
nice~~

**Comment by Liima** [comment]
I tried your suggestion soumith, and I got:

CMake Warning:
Manually specified variables were not used by the project:
WITH_LUAJIT20

and then the same error as above.

**Comment by DrNightmare** [comment]
Why is this issue closed?

I am still getting the same error output as @Liima even after doing:
`TORCH_LUA_VERSION=LUAJIT20 ./install.sh`
as per the suggestion by @soumith

**Comment by maxsombra** [comment]
i got the same error 

 TORCH_LUA_VERSION=LUAJIT20 ./install.sh 

in a VM ubuntu

**Comment by oncukayalar** [comment]
blade@runner:~/torch$ ./install.sh
Prefix set to /home/blade/torch/install
Installing Lua version: LUAJIT21
./install.sh: line 58: cmake: command not found

blade@runner:~/torch$ TORCH_LUA_VERSION=LUAJIT20 ./install.sh
Prefix set to /home/blade/torch/install
Installing Lua version: LUAJIT20
./install.sh: line 58: cmake: command not found

same error in Ubuntu 14.04 LTS

**Comment by oncukayalar** [comment]
sudo apt-get install cmake
./install.sh

**Comment by vadimostanin** [comment]
TORCH_LUA_VERSION=LUA52 ./install.sh
from README.md
Works for me

**Comment by OlegTsyba** [comment]
TORCH_LUA_VERSION=LUA52 ./install.sh

works for me, but luajit doesn't. What's the problem?

**Comment by soumith** [comment]
is it being installed on a VM? LuaJIT has history of failing to install on some VMs.

**Comment by OlegTsyba** [comment]
no, on a hardware, btw, it has a 32-bit processor.

**Comment by soumith** [comment]
32-bit, that's probably it. We didn't really test our build flags with 32-bit. Maybe there has to be something tweaked there....

**Comment by fishhf** [comment]
Same problem in linux mint 17.2 32bit, not vm.
Used LUAJIT20 and seems to work.

**Comment by firmread** [comment]
I had the same problem running on linux 32 bit
`TORCH_LUA_VERSION=LUA52 ./install.sh`
solved it as per @OlegTsyba mentioned

**Comment by sandeeppalakkal** [comment]
TORCH_LUA_VERSION=LUA52 ./install.sh worked for me. I have Lubuntu 14.04 32 bit version in my laptop.

**Comment by alimurreza** [comment]
It's possible that some of the submodules (lucarocks, ) are not fetched before doing the ./install.sh.
git clone --recursive to download the sub modules, then run the ./install.sh

**Comment by rabi1993** [comment]
Even after command `TORCH_LUA_VERSION=LUA52 ./install.sh`
  i am getting following error
Prefix set to /home/necuser/torch/install
```
Installing Lua version: LUA52
CMake Error: The current CMakeCache.txt directory /home/necuser/torch/build/CMakeCache.txt is different than the directory /opt/torch/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt

```

**Comment by rabi1993** [comment]
I found a solution first run` ./clean.sh ` from (https://github.com/torch/distro)
and then TORCH_LUA_VERSION=LUA51 ./install.sh
Got resolved issue for me

**Comment by shahabe** [comment]
I still have the same problem. 
Running on AWS instance. 
`TORCH_LUA_VERSION=LUA51 ./install.sh` does not work either.
