### ISSUE TITLE
Build leaves repo in unclean state

### ISSUE THREAD

**Issue by LinusU** [torch/distro#36]
After cloning and running `./install.sh` the working directory is left in a dirty state. This is not a problem with `torch/distro` itself but some of the submodules is leaving `build/` directories that isn't in the `.gitignore`.

- [x] exe/qtlua
- [x] extra/audio
- [x] extra/cunnx
- [x] extra/cutorch
- [x] extra/nn
- [x] extra/nngraph
- [x] extra/nnx
- [x] pkg/optim
- [x] pkg/paths
- [x] pkg/qttorch
- [x] pkg/sys
- [x] pkg/torch

In addition; these two packages have more files than only `build/`.

- [x] extra/threads
- [x] pkg/sundown

My specific use case of this is to install Torch via Ansible (automation software, like Puppet or Chef) and support reruns (aka. incremental builds). The idea is that it runs `git pull` again and if any new commits where added it will run `install.sh` again. This is currently failing with `Local modifications exist in repository`.

If we think that the correct way to fix this is to add `.gitignore` files to all the repos, I'd be happy to send pull requests to them all. Maybe there is a way to only add one `.gitignore` in this repo but I feel that adding it to every repo is the right way™ to do it.

**Comment by LinusU** [comment]
I just saw that the `.gitignore` in this repo actually lists `*/*/build`. Unfortunately that doesn't work since it's in a submodule :(

I'm taking this as a hint to that this is desired behaviour thought :)

**Comment by LinusU** [comment]
oops, those pull requests was not meant to go against my own fork, try again...

**Comment by LinusU** [comment]
Ok, so I've submitted pull request to all affected repos. Just need them accepted and then we can bump the commit we are pointing to here...

**Comment by LinusU** [comment]
Hurray! All pull requests have been merged.Thank you **soumith** and **nicholas-leonard** for the quick pulls!

@soumith Do you want a pull request for updating the pointers to the submodules?

**Comment by soumith** [comment]
@LinusU I'll do that now, after verifying all smoke tests pass. thanks a lot for the PR.

**Comment by LinusU** [comment]
No problem, thank you for your quick response :+1:
