### ISSUE TITLE
Global install

### ISSUE THREAD

**Issue by LinusU** [torch/distro#42]
It would be really nice if torch could have an optional step to install itself globally. This is usually the `sudo make install` step.

Basically it would copy most of the folders from the `install/` folder to `/usr/local/`. This would allow torch to be used by all users on the system, but most importantly, it wouldn't require the `torch-activate` script which is causing all kinds off headaches, especially with provisioning tools like Ansible.

**Comment by soumith** [comment]
The installer v1 was actually a global install. However, for us to deal with the side-effects of a global install, especially when people upgraded, was a huge pain, and there were way too many side-effects.

If you really want to do a global install for yourself, you can simply change this line:
https://github.com/torch/distro/blob/master/install.sh#L4

to /usr/local

**Comment by LinusU** [comment]
That's cool!

Could this issue be open for me to make a pull request for the script to accept `--prefix=`? Would that be accepted?

**Comment by soumith** [comment]
yea, it'll be accepted. instead of --prefix=, you might want to read a global env, so:
PREFIX=/usr/local ./install.sh

**Comment by LinusU** [comment]
Yes, global env sounds good. I was thinking of the `./configure` style.

**Comment by LinusU** [comment]
Hmm, there are some issues with this.

- It creates the file `$PREFIX/install.log`
- I want to run only `make install` with `sudo`, not the other parts
