### ISSUE TITLE
PATH manipulation in install script

### ISSUE THREAD

**Issue by soumith** [torch/distro#48]
Reported by @Phyks here: https://github.com/torch/torch7/issues/419

Hi,

The install script currently prepends torch install directory to the $PATH variable, in our .bashrc/.zshrc. However, I think it should not prepend but append.

Indeed, $PATH is parsed from left to right, and the directory on the left has then the highest priority. For a local install, the install directory is easily accessible (by the user, and by malicious scripts / users), which can put their some executables with the same names as common ones (say cd or even worse ssh) and the original ones will be hidden, which results in a security risk.

Moreover, for ZSH, I think that the $PATH definition should go to .zshenv and not .zshrc (at least, the prepending did not work on my setup because my $PATH definition is in .zshenv and there is no such things in .zshrc so the lines were not added correctly).

Thanks

**Comment by Phyks** [comment]
After discussion in the other issue, it seems that prepending to `PATH` is necessary to take over system-wide installs.

However, I am feeling that if `luarocks` is installed systemwide and the used `luarocks` is the one from Torch and not the system one, it will most likely work for `Torch` but may break other use cases on the system (which should rely on the system-wide install).

That is why I think it would be better to append, and find a virtualenv-like behavior to ensure Torch works correctly. Plus this mitigate the security risk in having a user-writeable path as first one of the `PATH`.

**Comment by gcr** [comment]
If a malicious process can write a bad binary to the user's `~/torch/install/bin` folder, it can also write to their `~/.bashrc`, which is a much easier attack. This isn't a security risk. [Code execution results in code execution](http://blogs.msdn.com/b/oldnewthing/archive/2007/08/07/4268706.aspx)

**Comment by Phyks** [comment]
Ok, the security concern can be discussed. My point is that a virtual env is enabled on-demand, using an activation script, whereas this modification is permanent.

I still consider it a bad practice, as it can also potentially break system-wide install.

**Comment by odellus** [comment]
I found I couldn't modify my PATH variable from `~/.bashrc` because `$/path/to/torch/install/bin/torch-activate` hard coded in PATH when it was installed.  Not cool. Not cool at all folks. :-1: on that bs.

**Comment by soumith** [comment]
@odellus ouch! Any better solution that you offer? We followed what Anaconda does, and anaconda is pretty mature / well-used, so it seemed okay.

**Comment by fmassa** [comment]
@soumith I think the problem is [here](https://github.com/torch/distro/blob/master/install.sh#L73), because `luarocks path --bin` overwrites the value of `PATH`.

**Comment by soumith** [comment]
hmmm, we dont really need that. should we just remove it?

**Comment by fmassa** [comment]
well, it also exports `LUA_PATH` and `LUA_CPATH`

**Comment by fmassa** [comment]
maybe changing `luarocks path --bin` by `luarocks path` would be enough ?

**Comment by soumith** [comment]
@fmassa yea you're right. that fixes it.

**Comment by soumith** [comment]
@odellus sorry about that, we fixed it.

**Comment by fmassa** [comment]
@soumith I think the original issue of this thread (prepending/appending the torch install path in [here](https://github.com/torch/distro/blob/master/install.sh#L143)) is still open, right ?

**Comment by soumith** [comment]
I suppose, but the issue is dead / wont-fix.

**Comment by odellus** [comment]
Thanks for the fix! Much appreciated! :+1:

**Comment by odellus** [comment]
A lot of people say a lot of great things about Anaconda. I have never been one of them.

I would say that Anaconda is stable if you make the assumption that the user can't figure out how to configure/install `gcc`, since a `numpy` dependency on `gcc` is the only reason Anaconda exists. So users who do crazy stuff like add things to `~/.bashrc` to customize their `PATH` so they can call `/path/to/zbs-torch/zbstudio.sh` from anywhere never really report bugs like this because they just `pip install numpy` in Linux. :smile:

**Comment by soumith** [comment]
@odellus it so happens that as a maintainer of a (very mildly) popular framework, one quickly tends to catering to the lowest common denominator when designing the "Download and Install" section. Torch's install used to be more normal / clean, but too many people couldn't figure out some things that we take for granted.
