### ISSUE TITLE
sub-modules aren't updated on install?

### ISSUE THREAD

**Issue by jonathantompson** [torch/distro#51]
OK, so I didn't realize that install.sh wouldn't pull the latest commits and install those.  It took me (honestly) about 2 hours to realize why a "fresh" install of torch wasn't installing the latest cudnn commit.  This is partly my stupidity, but also I really wonder why install.sh and update.sh aren't the same thing.

So, is having "install.sh" AND "update.sh" confusing to anyone else?  I feel like this "install.sh" should at least prompt a call to "update.sh" (i.e. ask the user if they want to update sub-repos to the latest version).  Somehow I think this is more intuitive.  Am I crazy?  Or put another, I know I'm crazy...  but am I crazy about this?

**Comment by soumith** [comment]
udpate.sh is run by the maintainer of distro to update the commits of each submodule, and push it upstream.

install.sh installs the last known stable commit that was set by the maintainer.

**Comment by soumith** [comment]
whenever I update the commits, I do this:
./update.sh
./clean.sh
./install.sh
./test.sh
git push

**Comment by jonathantompson** [comment]
But I don't see git pull anywhere in install.sh...

**Comment by soumith** [comment]
https://github.com/torch/distro/blob/master/install.sh#L44

**Comment by jonathantompson** [comment]
Ohhhhh...  OK, so the submodules lag behind depending on when you (or someone else) decides the main branch is stable?

**Comment by jonathantompson** [comment]
hmmmm...  I expected sub-repos to always point to the HEAD of nn, cunn, etc.  Is this not a good idea?

**Comment by soumith** [comment]
yep

**Comment by jonathantompson** [comment]
yep they do, or yep this is not a good idea?

**Comment by soumith** [comment]
the submodules lag behind depending on when you (or someone else) decides the main branch is stable?
Yes.

I expected sub-repos to always point to the HEAD of nn, cunn, etc. Is this not a good idea?
No, I dont think so. As torch grows, parts of the distro might go unstable without being noticed (I've been slowly adding contbuild but still no contbuild for cutorch / cunn and a few other core modules. )

**Comment by jonathantompson** [comment]
OK, so we're back to the old pattern of developers needing to maintain nn, cunn, etc versions themselves if they want the latest "development" branch.  That kind of makes this repo less appealing for most active developers then.  Right?

**Comment by soumith** [comment]
yea, it does which does suck. I can create a distro fork for devels, but the users are the ones where all the energy is drained supporting. I usually install distro, and whatever packages I need to develop, I clone separately.

**Comment by jonathantompson** [comment]
Yeah, that's what I used to do.  I was hoping this repo would put everything in one place.

It's OK though.  It was my misconception that brought this up in the first place.  Separate repo clones it is then :-)
