### ISSUE TITLE
Penlight dependency error

### ISSUE THREAD

**Issue by lakehanne** [torch/distro#53]
Following the instructions [here](http://torch.ch/docs/getting-started.html) for my installation on Ubuntu 14.04.

I got an error when I execute the third line:

>Updating manifest for /home/lex/torch/install/lib/luarocks/rocks
dok scm-1 is now built and installed in /home/lex/torch/install/ (license: BSD)

>Missing dependencies for trepl:
penlight >= 1.1.0

>Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest

>Error: Could not satisfy dependency: penlight >= 1.1.0

I tried sourcing bashrc and my profile, installed `penlight` with luarocks and did

<pre class="terminal"><code>cd ~/torch; ./install.sh</code></pre>

all over. But I still got the same error. Would appreciate your help.

**Comment by soumith** [comment]
assuming this was a temporary network issue and is fixed now.

**Comment by gpleiss** [comment]
I'm now getting this error.

**Comment by gpleiss** [comment]
Never mind! `rm -rf ~/.cache/luarocks` did the trick :grin:

**Comment by lim0606** [comment]
I'm now getting this error, too.
