### ISSUE TITLE
wrong cuda detection on ubuntu 12.04

### ISSUE THREAD

**Issue by MMesch** [torch/distro#54]
Hi everyone,

the installation script failed on my machine because install.sh detects nvidia-smi although I don't have CUDA installed. The script tries to compile cutorch but can't find the libraries then. I fixed it by explicitely removing the if ' [ -x "$path_to_nvcc" ] || [ -x "$path_to_nvidiasmi" ] ' blocks. Maybe this helps someone who has a similar problem.

These are the critical lines that wrongly indicate the presence of CUDA on my system:

    set +e 
    path_to_nvcc=$(which nvcc)
    path_to_nvidiasmi=$(which nvidia-smi)
    set -e 

    if [ -x "$path_to_nvcc" ] || [ -x "$path_to_nvidiasmi" ]

**Comment by iraadit** [comment]
Thanks a lot !

**Comment by soumith** [comment]
Made the cuda detection to be only based on nvcc. thanks for reporting this.
Fixed via https://github.com/torch/distro/commit/31f3f8a52bb44da1e4d9e6b02def00c3ba532a2a
