### ISSUE TITLE
luajit ffi

### ISSUE THREAD

**Issue by MMesch** [torch/distro#55]
I managed to install the self-contained torch distro package. However, the final lua doesn't seem to have the 'ffi' package, even though it should belong to luajit, which is installed.

I have a ffi.lua in:

torch/extra/argcheck/benchmark/torch9ffi.lua
torch/extra/argcheck/benchmark/torch9luaffi.lua
torch/extra/cudnn/ffi.lua
torch/extra/signal/ffi.lua

but these are apparently not in the path if source torch-activate is executed.

require('ffi') therefore fails

Any ideas?

**Comment by soumith** [comment]
ffi is an inbuilt package in luajit. it does not need separate installation.

**Comment by MMesch** [comment]
OK thanks working now!
