### ISSUE TITLE
require 'cutorch' takes 10s in local install

### ISSUE THREAD

**Issue by szagoruyko** [torch/distro#6]
So I cleaned the old global install, switched to local and loading cutorch with it takes 10s like it was compiled with debug options. Old installation was taking only 1s. Tried several times from scratch. Another machine with local install (4 Titans too) seems to be ok.
Don't know how to fix this.
nvprof with ```nvprof th -e "s = torch.tic(); require 'cutorch'; print(torch.toc(s))"```:

```
==24474== Profiling result:
Time(%)      Time     Calls       Avg       Min       Max  Name
100.00%  185.41us        12  15.450us  1.1200us  165.95us  [CUDA memcpy HtoD]

==24474== API calls:
Time(%)      Time     Calls       Avg       Min       Max  Name
 68.31%  7.19589s        12  599.66ms  147.99us  2.41770s  cudaDeviceEnablePeerAccess
 23.94%  2.52212s        14  180.15ms  7.3370us  2.52103s  cudaMalloc
  7.70%  810.81ms         4  202.70ms  119.40ms  235.93ms  cudaFree
  0.04%  4.6234ms       664  6.9620us     127ns  291.77us  cuDeviceGetAttribute
  0.01%  557.94us         8  69.743us  67.168us  74.313us  cuDeviceTotalMem
  0.00%  450.06us         8  56.257us  52.607us  71.948us  cuDeviceGetName
  0.00%  194.42us        12  16.201us  4.8500us  104.35us  cudaDeviceCanAccessPeer
  0.00%  182.14us        12  15.178us  6.8660us  40.687us  cudaMemcpy
  0.00%  27.852us        32     870ns     434ns  3.3870us  cudaEventCreateWithFlags
  0.00%  17.988us        40     449ns     257ns  2.2410us  cudaDeviceGetAttribute
  0.00%  15.284us        10  1.5280us     300ns  2.1950us  cudaSetDevice
  0.00%  9.8570us         5  1.9710us  1.2150us  3.3630us  cudaGetDevice
  0.00%  2.4080us        12     200ns     137ns     321ns  cuDeviceGet
  0.00%  1.2470us         3     415ns     189ns     797ns  cuDeviceGetCount
  0.00%     722ns         1     722ns     722ns     722ns  cudaGetDeviceCount
  0.00%     618ns         1     618ns     618ns     618ns  cuInit
  0.00%     363ns         1     363ns     363ns     363ns  cuDriverGetVersion
```

**Comment by zhangxiangxiao** [comment]
I used to have this issue with some particular version of NVidia driver (343.36), but when I downgraded it to 343.22 it became normal. Not sure whether this is something reproducible.

**Comment by szagoruyko** [comment]
I've been using this driver (340.29) and CUDA 6.5 for months now and it was normal.

**Comment by szagoruyko** [comment]
So I've reinstalled torch and cutorch several times from the clones I had before (repeated several times luarocks make) and it wokred. Superweird.

**Comment by szagoruyko** [comment]
Maybe it's just me but I've been suffering since I moved to this local install. The issue is still there.

**Comment by szagoruyko** [comment]
Had to run load speed test for each commit to identify that this commit
https://github.com/torch/cutorch/commit/b3646e1975e4886b8a1ca4c0f352ad890e9d2274 was the culprit. So it's not this repo, closing.
