### ISSUE TITLE
Issue while trying to display an image in Torch7

### ISSUE THREAD

**Issue by fernandoc1** [torch/distro#63]
I'm trying to display an image in Torch7 with the following command sequence:

th> require 'image'
th> i = image.lena()
th> image.display(i)

However, I'm facing the following issue:

/home/fccoelho/torch/install/share/lua/5.1/trepl/init.lua:383: module 'qt' not found:No LuaRocks module found for qt

Do someone knows why?

**Comment by soumith** [comment]
To use qt interface, start torch with qlua instead of th

**Comment by fernandoc1** [comment]
It would be nice if this info is added to the tutorial.
Many thanks. That worked.
