### ISSUE TITLE
Could not satisfy dependency: luaffi

### ISSUE THREAD

**Issue by tornadomeet** [torch/distro#64]
hello, i just installed torch follow http://torch.ch/docs/getting-started.html, but it output the error message, and i tried many times, like:rm -rf ~/.cache/luarocks && ./install.sh, but didn't work.   
so what's wrong with the  Installation? ths~
```python
Missing dependencies for nn:
luaffi 

Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /home/work/wuwei/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /home/work/wuwei/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest

Error: Could not satisfy dependency: luaffi
```

**Comment by tornadomeet** [comment]
i just remove the line https://github.com/torch/nn/blob/master/rocks/nn-scm-1.rockspec#L18, then it's ok and 'nn' can work now.
i'm not familiar with torch, so don't know the real reson. closed first.

**Comment by soshiant1992** [comment]
i have the same problem is there any other workaround ?

**Comment by soshiant1992** [comment]
Missing dependencies for itorch:
lbase64 
luacrypto 
uuid 
lzmq >= 0.4.2

this will happen isn't it because of this workaround?

**Comment by naba89** [comment]
I had the same issue. The problem for me was I was behind a proxy server and while running the command 

`sudo ./install.sh`

I got the same error. Solved it by exporting http_proxy and https_proxy environment variables and adding the -E flag to the above command.

`export http_proxy=http://<ip>:<port>`
`export https_proxy=https://<ip>:<port>`
`sudo -E ./install.sh`

Hope it helps!

**Comment by soshiant1992** [comment]
yes it was proxy problem and from the first step of the installation 
this problem had to be alleviated .and it works now
i'm in iran and i dont know why i have to use proxy to download these stuff

**Comment by MammadTavakoli** [comment]
I am from Iran to. but I cannot do that.
@soshiant1992  if you can call me to solve this problem.
m.tavakoli@gmail.com
