### ISSUE TITLE
FFI.lua:49: attempt to call global 'unpack' (a nil value)

### ISSUE THREAD

**Issue by yjernite** [torch/distro#68]
Hello,
  I just re-installed Torch using the instructions from [(https://github.com/torch/distro)], with the TORCH_LUA_VERSION=LUA52 option (other Lua versions were causing problems with trebl). Most of my installation is running, except for cutorch: I get an "attempt to call global 'unpack' (a nil value)" error.
 

```
th> require 'cutorch'
/home/yj426/Torch/share/lua/5.2/trepl/init.lua:383: /home/yj426/Torch/share/lua/5.2/cutorch/FFI.lua:49: attempt to call global 'unpack' (a nil value)
stack traceback:
	/home/yj426/Torch/share/lua/5.2/trepl/init.lua:500: in function </home/yj426/Torch/share/lua/5.2/trepl/init.lua:493>
	[C]: in function 'error'
	/home/yj426/Torch/share/lua/5.2/trepl/init.lua:383: in function 'require'
	[string "_RESULT={require 'cutorch'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/yj426/Torch/share/lua/5.2/trepl/init.lua:650: in function 'repl'
	/home/yj426/Torch/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: in ?	
```

Would someone have an idea of what is going on there?

Best,
Yacine

**Comment by soumith** [comment]
hey Yacine,

this command will fix your issues.

luarocks install cutorch

**Comment by soumith** [comment]
(also fixing it in distro right now)

**Comment by yjernite** [comment]
Thanks!
