### ISSUE TITLE
Auto-update function?

### ISSUE THREAD

**Issue by hughperkins** [torch/distro#71]
Two related observations:
1. would be nice to be able to do `torch-update`, and it will update at least torch7, nn, cutorch, cunn, to latest version
2. would be nice if installing distro automatically installed the latest versions :-)  Currently I think that the version are set in the git submodules?  And so we dont always get the latest versions, and have to build twice?

**Comment by soumith** [comment]
installing distro installs the most recent stable versions. everytime I update distro, I run the full suite of tests to make sure everything's okay. distro is for user-deployment, and hence this is suited.
i'm introducing named-versions soon.

**Comment by hughperkins** [comment]
Hmmm... well.... so....a problem I face is, eg with the THNN changes, distro hasnt changed yet, but clnn will have changed, following a merge, so we get the scenario:
- someone installs with distro (gets the old version of nn, pre-merge)
- then they install cltorch, clnn, which isnt currently part of distro, and get the new, post-merge version

Of course, in this scenario, clnn doesnt work.

**Comment by hughperkins** [comment]
So, there seem to be a few options for this:
1. leave it as it is. I deal with the upgrade bugs as and when they occur
2. make it easy for people to update to latest cutting-edge version of at least torch, nn, eg by providing a `torch-upgrade` script in distro.
3. add cltorch and clnn to distro :-)

I think option 1 is not ideal.  Option 3 is borderline perhaps.  Option 2 seems relatively easy :-)

**Comment by hughperkins** [comment]
Closing this, and reopening in the opposite direction.
