### ISSUE TITLE
Move install-deps.sh into distro?

### ISSUE THREAD

**Issue by hughperkins** [torch/distro#73]
Hi Soumith,

I want to instal la specific version of distro, always the sam version.

So, I'm cloning distro, then checking out, a specific hash.

However, install-deps then comes down from an unknown version for now.

thinking, maybe could be possible to move `install-deps` into `distro`?

Hugh

**Comment by soumith** [comment]
This is a great idea. probably should've been done long ago.

**Comment by hughperkins** [comment]
Cool :-)
