### ISSUE TITLE
Setting LD_LIBRARY_PATH in `torch-activate` stores up Mac build pain

### ISSUE THREAD

**Issue by hughperkins** [torch/distro#77]
Setting LD_LIBRARY_PATH in `torch-activate` stores up Mac build pain, since rpath issues wont tend to surface, for torch-based projects, until someone tries to build on a Mac.  Even travis doesnt fail builds, with LD_LIBRARY_PATH set, which will fail on many end-user computers.

Currently, I am patching out the LD_LIBRARY_PATH vars in my own travis builds, and also in my local system.  My own local system seems to work just fine without it.  travis now fails to build, which at least gives me a chance to notice and diagnose and fix the problem.

- patching of `torch-activate` in travis  https://github.com/hughperkins/pytorch/blob/dd2625e8c8b307478249fc7801ccedf0f276ab4b/travis/install-torch.sh#L19-L20
- rpath-less mac build succeeding in travis, disguised by the LD_LIBRARY_PATH being present  https://travis-ci.org/hughperkins/pytorch/builds/113223435  LD_LIBRARY_PATH  https://travis-ci.org/hughperkins/pytorch/builds/113223435#L820
- correctly failing, after removing LD_LIBRARY_PATH  https://travis-ci.org/hughperkins/pytorch/builds/113243547  LD_LIBRARY_PATH removed https://travis-ci.org/hughperkins/pytorch/builds/113243547#L308-L309  load failures https://travis-ci.org/hughperkins/pytorch/builds/113243547#L742-L744
- now building, with RPATH :-)  https://travis-ci.org/hughperkins/pytorch/builds/113287460  linker command to set rpath https://travis-ci.org/hughperkins/pytorch/builds/113287460#L421

It seems that it could plausibly be useful to tentatively consider removing LD_LIBRARY_PATH from `torch-activate`, at least on build machines and so on, and possibly, sooner or later, from distro itself?

**Comment by soumith** [comment]
a very good idea, something i largely agree with. also will help fix issues such as: https://github.com/torch/image/issues/137

how can I help?

**Comment by hughperkins** [comment]
> how can I help?

Hmmm, I'm not sure.  I guess my own pain-point on this matter is already resolved; I already removed LD_LIBRARY_PATH from my own system, and from all my travis builds.  It seems there are a few options really:
1. let everyone independently discover this for themselves (it's taken me 6-9 months of weird Mac build issues, which I've been largely powerless to solve, not having a Mac...)
2. create an faq for torch module developers somewhere.  this might also include things like FindCUDA
3. throw caution to the wind, and just remove LD_LIBRARY_PATH from torch-activate, and see if anyone complains :-P
4. remove LD_LIBRARY_PATH from all your own systems and builds, see if anything weird happens, move to step 3

**Comment by hughperkins** [comment]
On the whole, I guess option 2 is maybe both the safest, and the most positive perhaps?

**Comment by hughperkins** [comment]
Well, I finally got all my Mac builds to pass, in the absence of LD_LIBRARY_PATH :-D  https://travis-ci.org/hughperkins  After pondering a bit, this issue is maybe more something for torch module devs to be aware of than something that should be changed in distro.  Since, there may be some percentage of users for whom LD_LIBRARY_PATH increases the success rate of stuff working.  So, I'll close it I think.
