### ISSUE TITLE
error loading module 'libcutorch' after installation

### ISSUE THREAD

**Issue by jinjiren** [torch/distro#80]
I'm using CUDA 7.5, however, when running `luajit -llibcutorch`, it is said that `libcublas.so.6.5: cannot open shared object file: No such file or directory`.

I have been using Torch for a long time, and it worked well. However, today when I want to load cutorch, error appeared. I also tried delete Torch and reinstall, but it didn't work.

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```

```
luajit -llibcutorch                
luajit: error loading module 'libcutorch' from file '/home/jin/torch/install/lib/lua/5.1/libcutorch.so':
	libcublas.so.6.5: cannot open shared object file: No such file or directory
stack traceback:
	[C]: at 0x004786d0
	[C]: at 0x004678d0
	[C]: at 0x00406620
```

**Comment by soumith** [comment]
you must have some lingering old files from a previous CUDA installation.

**Comment by jinjiren** [comment]
@soumith Thank you very much for your reply.
Could you tell me how to delete those files? I think I just deleted the /usr/local/cuda-6.5 folder when I installed CUDA 7.5.

**Comment by soumith** [comment]
great, thanks for letting me know, in the future this info might help someone.
