### ISSUE TITLE
Cannot install because of broken lzmq

### ISSUE THREAD

**Issue by albertz** [torch/distro#82]
lzmq (which is a dependency of iTorch) fails to compile because it selects wrong ZMQ.

I reported that upstream here: https://github.com/zeromq/lzmq/issues/45

Do I really need iTorch? Maybe the install script can just continue and skip this?

**Comment by albertz** [comment]
Oh, I just realized, I guess it actually does it, i.e. it ignores this error? This is a bit confusing because it seems like it was the last thing it did.

Maybe add some final message at the end of the install script like "installation finished successful"?

**Comment by soumith** [comment]
removed itorch from default install via https://github.com/torch/distro/commit/92af9df13653733f28adbc2eac801363236d24ff
