### ISSUE TITLE
Installed successfully but  require 'nn' failed?

### ISSUE THREAD

**Issue by wangg12** [torch/distro#85]
I cloned this repo and built with install.sh. Then I typed `require 'nn'` in `th` shell, but got the following error:
```
/net/wanggu/torch/install/share/lua/5.1/trepl/init.lua:384: /net/wanggu/torch/install/share/lua/5.1/trepl/init.lua:384: /home/wanggu/.luarocks/share/lua/5.1/nn/test.lua:12: attempt to call field 'TestSuite' (a nil value)
stack traceback:
        [C]: in function 'error'
        /net/wanggu/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
        [string "_RESULT={require 'nn'}"]:1: in main chunk
        [C]: in function 'xpcall'
        /net/wanggu/torch/install/share/lua/5.1/trepl/init.lua:651: in function 'repl'
        ...nggu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
        [C]: at 0x00406670
```

My system is Ubuntu 14.04. My cuda version is 7.5 and my cudnn version is v4-prod. 

Anyone can give me a hand?

**Comment by soumith** [comment]
Do 

luarocks install torch 

See if that fixes things

**Comment by wangg12** [comment]
@soumith `luarocks install torch` is ok, but the error still exists.

**Comment by wangg12** [comment]
I tried clean.sh update.sh and reinstall. And I removed some packages in ·.local·. Then somehow it was solved. Maybe it is related to confusion between the local packages and the packages in where torch is installed.
