### ISSUE TITLE
cuDNN 5.0 support

### ISSUE THREAD

**Issue by thiell** [torch/distro#90]
Nvidia released cuDNN 5.0-rc (libcudnn.so.5), but Torch doesn't seem to be ready yet. I recompiled it from source but it didn't detect the change. Is cuDNN v4 hardcoded?

```
th> import 'cudnn'
...tras/torch/20160414-cbb5161/share/lua/5.1/trepl/init.lua:384: ...tras/torch/20160414-cbb5161/share/lua/5.1/trepl/init.lua:384: ...xtras/torch/20160414-cbb5161/share/lua/5.1/cudnn/ffi.lua:1278: 'libcudnn (R4) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.4 or libcudnn.4.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

stack traceback:
	[C]: in function 'error'
	...tras/torch/20160414-cbb5161/share/lua/5.1/trepl/init.lua:384: in function 'require'
	...tras/torch/20160414-cbb5161/share/lua/5.1/trepl/init.lua:321: in function 'import'
	[string "_RESULT={import 'cudnn'}"]:1: in main chunk
	[C]: in function 'xpcall'
	...tras/torch/20160414-cbb5161/share/lua/5.1/trepl/init.lua:651: in function 'repl'
	...h/20160414-cbb5161/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406000	
                                                                      [3.6003s]	
```

Thanks!

**Comment by soumith** [comment]
git clone https://github.com/soumith/cudnn.torch -b R5
cd cudnn.torch
luarocks make

**Comment by thiell** [comment]
@soumith ok thanks much! An automatic detection in torch/distro should be welcomed to ease the installation. I have been fighting a few days to install Torch on a large Cray cluster... it barely detects what's installed in non-standard paths (but everything is available in PATH or LD_LIBRARY_PATH...). I would love to see an automatic detection like with tools like autotools/cmake (ideally, I'm just saying :-)
thanks again for the quick reply.

**Comment by soumith** [comment]
@thiell torch uses cmake for all the path and version detection, except for a few bindings like cudnn.torch  which detection the library at runtime. Were particular packages painful to install, or all of them?

**Comment by thiell** [comment]
@soumith It could have been worse, Torch dependencies and to automate the installation (required) took me some time. Regarding Torch itself, I've seen worst (TensorFlow), but the first one is that it doesn't detect the compilers in PATH, but that's a common cmake problem, so  I had to do CC="$(which gcc)" CXX="$(which g++)"

Another thing is force these variables so that Torch won't override lua system paths:
export LUA_PATH=";;"
export LUA_CPATH=";;"
before ./install -b

Another blocking issue is that some environment variables are not taken into account by luarocks make, like for zlib PATHs, iTorch with ZeroMQ, libX11 and so on.  But I'm not a luarocks expert, maybe there is a way...

An example of successful change I had to make to install.sh ($EBROOTZEROMQ being my ZMQ prefix):
```diff
@@ -130,7 +130,7 @@
 if [[ `uname` == "Darwin" ]]; then
     cd ${THIS_DIR}/extra/iTorch         && $PREFIX/bin/luarocks make OPENSSL_DIR=/usr/local/opt/openssl/
 else
-    cd ${THIS_DIR}/extra/iTorch         && $PREFIX/bin/luarocks make
+    cd ${THIS_DIR}/extra/iTorch         && $PREFIX/bin/luarocks make ZMQ_DIR="$EBROOTZEROMQ"
 fi
 
 if [[ $SKIP_RC == 1 ]]; then

```

**Comment by thiell** [comment]
@soumith I confirm that building your R5 branch make cudnn works with cuDNN 5.0 RC, thanks again!

**Comment by zhFuECL** [comment]
R6 branch need cuda 8.0? How about 7.5?
