### ISSUE TITLE
iTorch causing --recursive checkout to fail

### ISSUE THREAD

**Issue by kramimus** [torch/distro#91]
Was working yesterday, looks like extra/iTorch needs to be removed again.

$ git clone https://github.com/torch/distro.git --recursive
Cloning into 'distro'...
remote: Counting objects: 886, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 886 (delta 3), reused 0 (delta 0), pack-reused 878
Receiving objects: 100% (886/886), 128.95 KiB | 0 bytes/s, done.
Resolving deltas: 100% (532/532), done.
Checking connectivity... done.
Submodule 'exe/env' (https://github.com/torch/env.git) registered for path 'exe/env'
Submodule 'exe/luajit-rocks' (https://github.com/torch/luajit-rocks.git) registered for path 'exe/luajit-rocks'
Submodule 'exe/qtlua' (https://github.com/torch/qtlua.git) registered for path 'exe/qtlua'
Submodule 'exe/trepl' (https://github.com/torch/trepl.git) registered for path 'exe/trepl'
Submodule 'extra/argcheck' (https://github.com/torch/argcheck.git) registered for path 'extra/argcheck'
Submodule 'extra/audio' (https://github.com/soumith/lua---audio.git) registered for path 'extra/audio'
Submodule 'extra/cudnn' (https://github.com/soumith/cudnn.torch.git) registered for path 'extra/cudnn'
Submodule 'extra/cunn' (https://github.com/torch/cunn.git) registered for path 'extra/cunn'
Submodule 'extra/cunnx' (https://github.com/nicholas-leonard/cunnx.git) registered for path 'extra/cunnx'
Submodule 'extra/cutorch' (https://github.com/torch/cutorch.git) registered for path 'extra/cutorch'
Submodule 'extra/fftw3' (https://github.com/soumith/fftw3-ffi.git) registered for path 'extra/fftw3'
Submodule 'extra/graph' (https://github.com/torch/graph) registered for path 'extra/graph'
Submodule 'extra/graphicsmagick' (https://github.com/clementfarabet/graphicsmagick.git) registered for path 'extra/graphicsmagick'
No submodule mapping found in .gitmodules for path 'extra/iTorch'

**Comment by soumith** [comment]
thanks, fixed now. there's a brief window of ~1 hour when i stepped out after pushing an update and the git somehow screwed up the submodules.
