### ISSUE TITLE
running install.sh failed

### ISSUE THREAD

**Issue by ZhengZhaoHeng** [torch/distro#93]
I ran the ./install.sh and met this error

`SOX_INCLUDE_DIR: SOX_INCLUDE_DIR-NOTFOUND
SOX_LIBRARIES: SOX_LIBRARIES-NOTFOUND
FFTW_INCLUDE_DIR: FFTW_INCLUDE_DIR-NOTFOUND
FFTW_LIBRARIES: FFTW_LIBRARIES-NOTFOUND
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FFTW_INCLUDE_DIR
   used as include directory in directory /home/moocos/torch/extra/audio
   used as include directory in directory /home/moocos/torch/extra/audio
FFTW_LIBRARIES
    linked by target "audio" in directory /home/moocos/torch/extra/audio
SOX_INCLUDE_DIR
   used as include directory in directory /home/moocos/torch/extra/audio
   used as include directory in directory /home/moocos/torch/extra/audio
SOX_LIBRARIES
    linked by target "audio" in directory /home/moocos/torch/extra/audio
    linked by target "sox" in directory /home/moocos/torch/extra/audio

-- Configuring incomplete, errors occurred!
See also "/home/moocos/torch/extra/audio/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.
Updating manifest for /home/moocos/torch/install/lib/luarocks/rocks
fftw3 scm-1 is now built and installed in /home/moocos/torch/install/ (license: BSD)

`

**Comment by soumith** [comment]
that's okay, this is an optional repo. you can still use torch as-is.
