### ISSUE TITLE
install-deps needs to support Ubuntu 16.04

### ISSUE THREAD

**Issue by meequz** [torch/distro#96]
Running `./install-deps` cause this:

`{a lot of output about clonning some repos by git}`
`Installing Lua version: LUAJIT21`
`./install.sh: line 59: cmake: command not found`

Has been tried out in Ubuntu MATE 16.04

**Comment by rue-ryuzaki** [comment]
install cmake

**Comment by meequz** [comment]
It is exactly what I did. But the script supposed to install all the deps in my system, so it is its work to handle missing `cmake`, and this error must not appear. This issue is about support Ubuntu 16.04 in the `install-deps` script.

**Comment by marioyc** [comment]
The same thing also happened to me, cmake and libreadline-dev weren't being installed which is weird since it should be installed at [this point](https://github.com/torch/distro/blob/master/install-deps#L164).
